@host = https://localhost
@port = 7208

@WorldTravel.API_HostAddress = https://localhost:7208


// Countries
###

GET {{WorldTravel.API_HostAddress}}/api/countries

###

@countryId=US

GET {{WorldTravel.API_HostAddress}}/api/countries/{{countryid}}


// Continents
###

GET {{WorldTravel.API_HostAddress}}/api/continents

###
@continentId=EU
GET {{WorldTravel.API_HostAddress}}/api/continents/{{continentId}}

###
