@host = https://localhost
@port = 7208
@WorldTravel.API_HostAddress = https://localhost:7208

### get all countries
GET {{WorldTravel.API_HostAddress}}/api/countries

### get country by id
GET {{WorldTravel.API_HostAddress}}/api/countries/en
### create new country
POST {{WorldTravel.API_HostAddress}}/api/countries
Content-Type: application/json

{
    "Id": "1234",
    "Name": "England",
    "Description": "A country in the EU",
    "ContinentId": "EU",
    "Population": 64000000,
    "NumberOfTourists": 50000
}
### delete country
DELETE {{WorldTravel.API_HostAddress}}/api/countries/eng

### get all continents
GET {{WorldTravel.API_HostAddress}}/api/continents

### get continent by id
GET {{WorldTravel.API_HostAddress}}/api/continents/eu

###

PATCH {{WorldTravel.API_HostAddress}}/api/countries/en
Content-Type: application/json

{
  
}

### create new city
POST {{WorldTravel.API_HostAddress}}/api/countries/US/cities
Content-Type: application/json

{
  "Name": "New York"
}

###
